CREATE TABLE "users" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "openId" varchar(64) NOT NULL UNIQUE,
  "name" text,
  "email" varchar(320),
  "loginMethod" varchar(64),
  "role" varchar(16) NOT NULL DEFAULT 'user' CHECK ("role" IN ('user', 'admin')),
  "avatarKey" varchar(500),
  "avatarUrl" varchar(750),
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  "lastSignedIn" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "workspaces" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(120) NOT NULL,
  "slug" varchar(80) NOT NULL UNIQUE,
  "createdById" integer NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "workspaceMembers" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workspaceId" integer NOT NULL,
  "userId" integer NOT NULL,
  "role" varchar(16) NOT NULL DEFAULT 'member' CHECK ("role" IN ('admin', 'member', 'viewer')),
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "workspace_member_unique" UNIQUE ("workspaceId", "userId")
);

CREATE TABLE "projects" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workspaceId" integer NOT NULL,
  "name" varchar(120) NOT NULL,
  "key" varchar(12) NOT NULL,
  "description" text,
  "accentColor" varchar(7) NOT NULL DEFAULT '#A55343',
  "logoKey" varchar(500),
  "logoUrl" varchar(750),
  "workflow" jsonb NOT NULL,
  "createdById" integer NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "workspace_project_key_unique" UNIQUE ("workspaceId", "key")
);

CREATE TABLE "projectMembers" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "projectId" integer NOT NULL,
  "userId" integer NOT NULL,
  "role" varchar(16) NOT NULL DEFAULT 'member' CHECK ("role" IN ('viewer', 'reporter', 'member', 'triage', 'admin')),
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "project_member_unique" UNIQUE ("projectId", "userId")
);

CREATE TABLE "milestones" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "projectId" integer NOT NULL,
  "name" varchar(120) NOT NULL,
  "targetDate" timestamptz,
  "status" varchar(16) NOT NULL DEFAULT 'planned' CHECK ("status" IN ('planned', 'active', 'released', 'archived')),
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "components" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "projectId" integer NOT NULL,
  "name" varchar(100) NOT NULL,
  "description" text,
  "ownerId" integer,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "component_project_name_unique" UNIQUE ("projectId", "name")
);

CREATE TABLE "labels" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "projectId" integer NOT NULL,
  "name" varchar(60) NOT NULL,
  "color" varchar(12) NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "label_project_name_unique" UNIQUE ("projectId", "name")
);

CREATE TABLE "issues" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "projectId" integer NOT NULL,
  "number" integer NOT NULL,
  "title" varchar(250) NOT NULL,
  "description" text,
  "expectedResult" text,
  "actualResult" text,
  "reproducibleSteps" text,
  "environment" text,
  "severity" varchar(16) NOT NULL DEFAULT 'major' CHECK ("severity" IN ('blocker', 'critical', 'major', 'minor', 'trivial')),
  "priority" varchar(16) NOT NULL DEFAULT 'medium' CHECK ("priority" IN ('urgent', 'high', 'medium', 'low', 'none')),
  "status" varchar(16) NOT NULL DEFAULT 'intake' CHECK ("status" IN ('intake', 'triage', 'in_progress', 'verify', 'done')),
  "resolution" varchar(24) CHECK ("resolution" IN ('fixed', 'duplicate', 'wont_fix', 'invalid', 'works_as_intended')),
  "reporterId" integer NOT NULL,
  "assigneeId" integer,
  "componentId" integer,
  "milestoneId" integer,
  "dueAt" timestamptz,
  "isReleaseBlocker" boolean NOT NULL DEFAULT false,
  "triagedAt" timestamptz,
  "resolvedAt" timestamptz,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "issue_project_number_unique" UNIQUE ("projectId", "number")
);

CREATE TABLE "issueLabels" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "issueId" integer NOT NULL,
  "labelId" integer NOT NULL,
  CONSTRAINT "issue_label_unique" UNIQUE ("issueId", "labelId")
);

CREATE TABLE "issueLinks" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "issueId" integer NOT NULL,
  "linkedIssueId" integer NOT NULL,
  "type" varchar(16) NOT NULL CHECK ("type" IN ('relates_to', 'duplicates', 'blocked_by', 'blocks')),
  "createdById" integer NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "issue_link_unique" UNIQUE ("issueId", "linkedIssueId", "type")
);

CREATE TABLE "issueActivity" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "issueId" integer NOT NULL,
  "actorId" integer,
  "type" varchar(80) NOT NULL,
  "message" text,
  "metadata" jsonb,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "comments" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "issueId" integer NOT NULL,
  "authorId" integer NOT NULL,
  "parentId" integer,
  "body" text NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "issueWatchers" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "issueId" integer NOT NULL,
  "userId" integer NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "issue_watcher_unique" UNIQUE ("issueId", "userId")
);

CREATE TABLE "attachments" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "issueId" integer NOT NULL,
  "uploadedById" integer NOT NULL,
  "storageKey" varchar(500) NOT NULL,
  "storageUrl" varchar(750) NOT NULL,
  "fileName" varchar(255) NOT NULL,
  "contentType" varchar(160) NOT NULL,
  "sizeBytes" integer NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "savedViews" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "projectId" integer NOT NULL,
  "ownerId" integer NOT NULL,
  "name" varchar(80) NOT NULL,
  "filters" jsonb NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "saved_view_owner_name_unique" UNIQUE ("projectId", "ownerId", "name")
);

CREATE TABLE "userPreferences" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL UNIQUE,
  "sidebarOrder" jsonb NOT NULL,
  "projectOrder" jsonb NOT NULL,
  "savedSearches" jsonb NOT NULL,
  "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "notifications" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer NOT NULL,
  "workspaceId" integer NOT NULL,
  "projectId" integer,
  "issueId" integer,
  "type" varchar(24) NOT NULL CHECK ("type" IN ('mention', 'assignment', 'watcher', 'status_change', 'system')),
  "title" varchar(180) NOT NULL,
  "body" text,
  "readAt" timestamptz,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "aiRecommendations" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "issueId" integer NOT NULL,
  "requestedById" integer NOT NULL,
  "model" varchar(100) NOT NULL,
  "summary" text NOT NULL,
  "suggestedSeverity" varchar(20),
  "suggestedLabels" jsonb NOT NULL,
  "duplicateCandidates" jsonb NOT NULL,
  "reproducibleSteps" text NOT NULL,
  "caveats" text NOT NULL,
  "confidence" integer NOT NULL,
  "state" varchar(24) NOT NULL DEFAULT 'pending_review' CHECK ("state" IN ('pending_review', 'applied', 'dismissed')),
  "reviewedById" integer,
  "reviewedAt" timestamptz,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX "workspace_member_user_idx" ON "workspaceMembers" ("userId");
CREATE INDEX "project_workspace_idx" ON "projects" ("workspaceId");
CREATE INDEX "project_member_user_idx" ON "projectMembers" ("userId");
CREATE INDEX "milestone_project_idx" ON "milestones" ("projectId");
CREATE INDEX "component_project_idx" ON "components" ("projectId");
CREATE INDEX "label_project_idx" ON "labels" ("projectId");
CREATE INDEX "issue_project_status_idx" ON "issues" ("projectId", "status");
CREATE INDEX "issue_project_severity_idx" ON "issues" ("projectId", "severity");
CREATE INDEX "issue_assignee_idx" ON "issues" ("assigneeId");
CREATE INDEX "issue_link_issue_idx" ON "issueLinks" ("issueId");
CREATE INDEX "issue_activity_issue_idx" ON "issueActivity" ("issueId");
CREATE INDEX "comment_issue_idx" ON "comments" ("issueId");
CREATE INDEX "issue_watcher_user_idx" ON "issueWatchers" ("userId");
CREATE INDEX "attachment_issue_idx" ON "attachments" ("issueId");
CREATE INDEX "saved_view_project_idx" ON "savedViews" ("projectId");
CREATE INDEX "notification_user_read_idx" ON "notifications" ("userId", "readAt");
CREATE INDEX "notification_issue_idx" ON "notifications" ("issueId");
CREATE INDEX "ai_recommendation_issue_idx" ON "aiRecommendations" ("issueId");

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW."updatedAt" = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER users_updated_at BEFORE UPDATE ON "users" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER workspaces_updated_at BEFORE UPDATE ON "workspaces" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER projects_updated_at BEFORE UPDATE ON "projects" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER issues_updated_at BEFORE UPDATE ON "issues" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER comments_updated_at BEFORE UPDATE ON "comments" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER saved_views_updated_at BEFORE UPDATE ON "savedViews" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER user_preferences_updated_at BEFORE UPDATE ON "userPreferences" FOR EACH ROW EXECUTE FUNCTION set_updated_at();
