import { CommandDialog, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList, CommandShortcut } from "@/components/ui/command";
import { useActiveProject } from "@/hooks/useActiveProject";
import { trpc } from "@/lib/trpc";
import { BarChart3, Bell, BookmarkPlus, Command, FileSearch, Filter, Home, KanbanSquare, ListTodo, Plus } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";

const routes = [{ label: "Overview", path: "/", icon: Home }, { label: "Issues", path: "/issues", icon: ListTodo }, { label: "Workboard", path: "/boards", icon: KanbanSquare }, { label: "Insights", path: "/analytics", icon: BarChart3 }, { label: "Inbox", path: "/notifications", icon: Bell }];
const defaultSidebar = ["/", "/issues", "/boards", "/analytics", "/notifications"] as const;
type SavedSearch = { id: string; name: string; query: string; status?: "intake" | "triage" | "in_progress" | "verify" | "done"; severity?: "blocker" | "critical" | "major" | "minor" | "trivial" };

export function savedSearchIssuePath(search: SavedSearch) { const params = new URLSearchParams(); if (search.query) params.set("q", search.query); if (search.status) params.set("status", search.status); if (search.severity) params.set("severity", search.severity); return `/issues${params.size ? `?${params}` : ""}`; }

export default function CommandPalette() {
  const [open, setOpen] = useState(false); const [search, setSearch] = useState(""); const [, setLocation] = useLocation();
  const { data, projectId, activeProject, chooseProject } = useActiveProject(); const preferences = trpc.personalization.get.useQuery(undefined, { retry: false }); const utils = trpc.useUtils();
  const savePreferences = trpc.personalization.updatePreferences.useMutation({ onSuccess: () => utils.personalization.get.invalidate() }); const issueQuery = trpc.issues.list.useQuery({ projectId: projectId ?? 0, pageSize: 12 }, { enabled: Boolean(projectId) });
  const savedSearches = (preferences.data?.savedSearches ?? []) as SavedSearch[]; const go = (path: string) => { setOpen(false); setSearch(""); setLocation(path); };
  const orderedProjects = [...(data?.projects ?? [])].sort((a, b) => { const ai = (preferences.data?.projectOrder ?? []).indexOf(a.id); const bi = (preferences.data?.projectOrder ?? []).indexOf(b.id); return (ai < 0 ? 99_999 : ai) - (bi < 0 ? 99_999 : bi); });
  const saveCurrent = () => { const query = search.trim(); if (query.length < 2) return; const next = [...savedSearches.filter(item => item.query.toLowerCase() !== query.toLowerCase()), { id: `saved-${Date.now()}`, name: `Search: ${query}`, query }]; savePreferences.mutate({ sidebarOrder: (preferences.data?.sidebarOrder ?? defaultSidebar) as ["/", "/issues", "/boards", "/analytics", "/notifications"], projectOrder: preferences.data?.projectOrder ?? [], savedSearches: next }); };
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setOpen(value => !value); } }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []);
  return <CommandDialog open={open} onOpenChange={setOpen} title="Navigate BugForge" description="Search pages, projects, issue filters, and saved searches." className="command-palette border-[#D8CDC0] bg-[#FFFCF7] text-[#1E1A18] dark:border-[#4A433D] dark:bg-[#211F1D] dark:text-[#F4EEE6]"><CommandInput value={search} onValueChange={setSearch} placeholder="Search pages, projects, or issues…" /><CommandList><CommandEmpty>No matching destination.</CommandEmpty><CommandGroup heading="Navigate">{routes.map(route => <CommandItem key={route.path} value={`go ${route.label}`} onSelect={() => go(route.path)}><route.icon /><span>{route.label}</span>{route.path === "/issues" && <CommandShortcut>G I</CommandShortcut>}</CommandItem>)}<CommandItem value="new issue" onSelect={() => go("/issues")}><Plus /><span>Create a new issue</span></CommandItem></CommandGroup><CommandGroup heading="Quick issue filters"><CommandItem value="untriaged intake reports" onSelect={() => go("/issues?status=intake")}><Filter /><span>Untriaged reports</span></CommandItem><CommandItem value="critical issues" onSelect={() => go("/issues?severity=critical")}><Filter /><span>Critical issues</span></CommandItem><CommandItem value="blocker issues" onSelect={() => go("/issues?severity=blocker")}><Filter /><span>Release blockers</span></CommandItem>{search.trim().length >= 2 && <CommandItem value={`save search ${search}`} onSelect={saveCurrent}><BookmarkPlus /><span>Save search “{search.trim()}”</span></CommandItem>}</CommandGroup>{savedSearches.length ? <CommandGroup heading="Saved searches">{savedSearches.map(item => <CommandItem key={item.id} value={`${item.name} ${item.query}`} onSelect={() => go(savedSearchIssuePath(item))}><BookmarkPlus /><span>{item.name}</span></CommandItem>)}</CommandGroup> : null}<CommandGroup heading="Projects">{orderedProjects.map(project => <CommandItem key={project.id} value={`${project.key} ${project.name}`} onSelect={() => { chooseProject(project.id); go("/"); }}><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: project.accentColor }} /><span>{project.key} · {project.name}</span>{activeProject?.id === project.id && <CommandShortcut>Active</CommandShortcut>}</CommandItem>)}</CommandGroup>{issueQuery.data?.items?.length ? <CommandGroup heading="Recent issues">{issueQuery.data.items.map(issue => <CommandItem key={issue.id} value={`issue ${issue.number} ${issue.title}`} onSelect={() => go(`/issues/${issue.id}`)}><FileSearch /><span className="truncate">#{issue.number} · {issue.title}</span></CommandItem>)}</CommandGroup> : null}</CommandList></CommandDialog>;
}
